### PR TITLE
some refactors

### PR DESCRIPTION
**Pull request by qinzuoyan**
including:
- fix build.sh and CMakeLists.txt to support customized boost
- recompile rrdb.thrift according to rDSN change

### CODE REVIEW

**Comment by imzhenyu** [comment]
several issues:

. why we need boost? we have used quite some effort to eliminate the dependency of boost before.
. instead of introducing a separated build.sh, can we embed the code generation commands into cmake scripts to make sure we can still use a single cmake to get things done?
. make sure the changes are workable on both windows and linux

**Comment by qinzuoyan** [comment]
@imzhenyu
- why we need boost? rrdb depends on libdsn.core.so, which depends on libboost_system.so, so we need to tell compiler (actually the linker) where to find the boost lib. Generally, if we use system boost to build rrdb, the boost lib can be found in system lib path; but if we use the customized boost (because rDSN uses the customized boost), we need to set -rpath option to specify the proper boost lib path.
- I don't embed the code generation commands into cmake script, because the rrdb.client.perf.h is modified, and can not be replaced directly. I add recompile_thrift.sh just for easy update when need.
- make sure the changes are workable on both windows and linux: I install vs2015 failed on my machine :-(, I'll try to install it again...

**Comment by imzhenyu** [comment]
Thx, @qinzuoyan  for "rDSN uses the customized boost?" I think we simply use the one from apt-get ...

**Comment by qinzuoyan** [comment]
@imzhenyu , apt-get the latest version is 1.53, maybe we need higher version such as 1.59; on the other hand, sometimes we don't have root privilege to install boost on servers.

**Comment by imzhenyu** [comment]
I c. Maybe another way is to adopt static link, as we have done on windows, so that no boost libs is needed anymore as long as we have libdsn.core.so. However, there seems some link problems on linux as @linmajia has tried before. Maybe you guys can try again ...:)

**Pull request merged**
