### PR TITLE
rrdb cluster

### PR DESCRIPTION
**Pull request by yejw5**
Add rrdb_cluster program to the rocksdb, which realizes the functions to create_app, drop_app, list_apps, list_app, list_nodes, stop_migration, start_migration, balancer and so on.

Request by Ye Jianwu, from Xiaomi

### CODE REVIEW

**Comment by imzhenyu** [comment]
Thanks Jianwu. What is difference between this project and the ddlclient project under rDSN? Seems quite similar to me...

**Comment by yejw5** [comment]
Hello Zhenyu. Sorry for my comment not detailed enough. This project integrate the command of ddlclient project under rDSN and the get, set, del functions in the clientlib project under rocksdb. The orginal idea is proposed by Zuo Yan, in order to make our operation to app more conveniently.

Here's the all usage information:

```
Usage:
    create:          create -name <app_name> -type <app_type> [-pc partition_count] [-rc replication_count]
    drop:            drop -name <app_name>
    list_apps:       ls [-status <all|available|creating|creating_failed|dropping|dropping_failed|dropped>] [-o <out_file>]
    list_app:        app -name <app_name> [-detailed] [-o <out_file>]
    list_nodes:      nodes [-status <all|alive|unalive>] [-o <out_file>]
    stop_migration:  stop_migration
    start_migration: start_migration
    balancer:        balancer -gpid <appid.pidx> -type <move_pri|copy_pri|copy_sec> -from <from_address> -to <to_address>
    use:             use [table-name]
    set:             set <hash-key> <sort-key> <value>
    get:             get <hash-key> <sort-key>
    del:             del <hash-key> <sort-key>
    exit:            exit
    help:            help

    partition count must be a power of 2
    app_name and app_type shoud be composed of a-z, 0-9 and underscore
    without -o option, program will print status on screen
    with -detailed option, program will also print partition state
```

Hope that it's helpful for our project!

**Comment by qinzuoyan** [comment]
The rrdb_cluster is a client tool to operate on rrdb such as create/drop/list/get/set. This tool is designed in sub-command mode, to provide user a convenient all-in-one tool.

**Comment by imzhenyu** [comment]
I see redundant code in these two projects. Can we separate them into two tools to avoid redundancy? Or, we may introduce a common cli tool, and make these two projects as two dynamic libraries to be loaded later into the same cli executable?

**Comment by qinzuoyan** [comment]
@imzhenyu , I have improved rDSN to separate ddlclient lib to make it reusable, as in https://github.com/imzhenyu/rDSN/pull/341 .  And I will fix this pull request to remove redundant code.

**Comment by qinzuoyan** [comment]
@imzhenyu , fix done, please review it.

**Pull request merged**
