### PR TITLE
fix apply checkpoint bug

### PR DESCRIPTION
**Pull request by qinzuoyan**
for #4

### CODE REVIEW

**Comment by qinzuoyan** [comment]
@imzhenyu , the rocksdb is not compatible with rDSN now, maybe caused by recent commits to rDSN

**Comment by imzhenyu** [comment]
@qinzuoyan Already fixed in https://github.com/imzhenyu/rocksdb/commit/a7d1bb1ab85785b6a8256f546b31d8458ab56e8b please update. There are still build break though on windows, see https://github.com/imzhenyu/rocksdb/issues/10

**Comment by imzhenyu** [comment]
Btw, why the last sequence in the version edit may be wrong?

**Comment by qinzuoyan** [comment]
the reason is: when LogAndApply(), the added new VersionEdit will record the real-time LastSequence, which is usually greater than LastFlushedSequence, because recent data is in memtable and commit-log, but we discard commit-log when do async-checkpoint.

**Comment by imzhenyu** [comment]
got it.

**Pull request merged**
